name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [7, 8, 11, 17]
    env:
      repo: "govpf/maven"
    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.7.0

    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./3/jdk-${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:3-jdk-${{ matrix.versions }}
          ${{ env.repo }}:3.6-jdk-${{ matrix.versions }}
